"""
Simple PDF export helper using ReportLab.
Fixes ImportError by not importing non-existent TableRow and uses standard ReportLab components.
Provides export_grid_pdf_template(filename, headers, grid, meta) used by TimetableService.export_to_pdf.
"""
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm

def export_grid_pdf_template(filename: str, headers: list, grid: dict, meta: dict):
    """
    filename: output path
    headers: list of timeslots, e.g. ["09:00-09:50", ...] OR ["P1: 09:00-09:50", ...]
    grid: dict day -> list of strings
    meta: dict with optional keys: title, created_by
    """
    title = (meta or {}).get("title", "Timetable")
    created_by = (meta or {}).get("created_by", "")

    # Build table data: header row is ["Day", header1, header2, ...]
    periods = len(headers)
    table_data = []
    header_row = ["Day"] + headers
    table_data.append(header_row)

    days = list(grid.keys())
    for d in days:
        row = [d]
        cells = grid.get(d, [""] * periods)
        # ensure length
        if len(cells) < periods:
            cells = cells + [""] * (periods - len(cells))
        for c in cells:
            row.append(c)
        table_data.append(row)

    # Create document
    doc = SimpleDocTemplate(filename, pagesize=landscape(A4), rightMargin=12*mm, leftMargin=12*mm, topMargin=12*mm, bottomMargin=12*mm)
    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(Paragraph(title, styles["Title"]))
    if created_by:
        story.append(Paragraph(f"Generated by: {created_by}", styles["Normal"]))
    story.append(Spacer(1, 6))

    # Table
    tbl = Table(table_data, repeatRows=1)
    style = TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#f3f4f6")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.black),
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("LEFTPADDING", (0,0), (-1,-1), 6),
        ("RIGHTPADDING", (0,0), (-1,-1), 6),
    ])
    tbl.setStyle(style)
    story.append(tbl)

    doc.build(story)